### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by diana-pilvar** [diana-pilvar/DM-materials-ELIXIR-EE#1]
# Welcome!

This is a roadmap for a project that creates web pages containing data management-related information, recommendations and know-how to help the researchers in Estonia to manage their data according to the funder's requirements. 
Where it should go https://elixir.ut.ee/

In order to get involved, please contact [diana.pilvar@ut.ee]. Currently working on FAIR principles F.

### Milestone 1: Achieved

- [x] Define Scope 

In Scope:

- Produce materials for ELIXIR-Estonia
  - Start with a life sciences approach
- Develop skillset
  - How to cooperate with people 
  - How to handle non-cooperative people
  - Learn leadership skills

#### Weekly goals

- Week 6
    - [x] Look over introduction

-  Week 7 
    - [x] mentor meeting
    - [ ]  F in FAIR draft
    - [x] Decide on visuals needed during meeting

- Week 8
    - [ ] Add visuals in F
    - [ ] A in FAIR draft

- Week 9
    - [x] mentor meeting
    - [x] Decide on visuals needed for A  during meeting

- Week 10
    - [ ] Add A visuals
    - [ ] I in FAIR draft

- Week 11 
    - [x] mentor meeting
    - [x] Decide on visuals needed for I  during a meeting

- Week 12
    - [ ] Add I visuals
    - [ ] R in FAIR draft

- Week 13
    - [x] mentor meeting
    - [x] Decide on visuals needed for R  during meeting

- Week 14
    - [ ] - Add R visuals

- Week 15 
    - [ ] mentor meeting
    - [ ] Review final version

- Week 16

### Weekly goals

- Week 6
  - [ ] Requirements for data management in Estonia 

- Week 7 - mentor meeting
- Week 8
- Week 9- mentor meeting
    - [ ] Requirements for data management in Europe

- Week 10
- Week 11 - mentor meeting
  - [ ] Programs available for writing DMP 
  - [ ] Comparisons between them. 
  - [ ] How to make accounts
  - [ ] Link to tutorials on how to use tools

- Week 12
- Week 13- mentor meeting

  - [ ] Create DCC template with good guiding keywords and phrases ( what to fill out in each field)

- Week 14

    - [ ] Create Horizon Europe template with good guiding keywords and phrases ( what to fill out in each field) 

- Week 15- mentor meeting

    - [ ] Create DMP templates as downloadable materials
    - [ ] Link DMP templates + Link to how to fill them out -Estonian resources 
    - [ ] Link to tips in zenodo https://doi.org/10.5281/zenodo.7736043 
    - [ ] Link to metadata and licensing materials on zenodo [https://zenodo.org/communities/elixir-ee/?page=1&size=20]

- Week 16

    - [ ] Review final version

- Post OLS
    - Local grants applications are in the spring
    - Every spring check for requirements
    - Check European commission requirements too

### Milestone 4: Personal skills

- [ ] Read Data stewardship for open science
- [ ] Attend OLS skill-ups about leadership
    - [x] Open Science Garden I
    - [x] Community design for inclusivity
    - [x] Open Leadership: Academia, industry and beyond!
    - [ ] Open-source software
    - [x] Diversity and Inclusion & Ally skills
    - [ ] Self-care & Social call
    - [ ] Open Science III: Next steps - applying FAIR research principles

**Optional:**

- [ ] Never Eat Alone - Keith Ferrazzi
- [ ] Atomic Habits - James Clear 
- [ ] How to Make Friends and Influence People - Dale Carnegie 
- [ ] Never Split the Difference - Chris Voss
- [ ] No hard feelings - Liz Fosslien, Mollie West Duffy
- [ ] Coursera Data management course
